###############################################################################
# VMs configs
###############################################################################
vms:
  aem6.3-author-vm:
    enabled: false
  aem6.3-publish-vm:
    enabled: true