###############################################################################
# VMs configs
###############################################################################
vms:
  # CQ5 VMs: 6.0 & 6.1 
  # Each VM has a Author & a Publish instance
  # Allocate 3Gb to the VM & 1 CPUs
  # SSH Ports: 2243+
  # IP: 192.168.2.199-
  #
  #######################################################
  # For Ubuntu update the configs - 
  # box_os: "ubuntu"
  # box_name: "opscode_ubuntu-14.04_chef-provisionerless"
  # box_url: "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"
  #######################################################
  # For Centos - 
  # box_name: "centos-7.2-x64.box"
  # box_url: "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box"
  ###############################################################################################
  # AEM 6.3 VMS
  ###############################################################################################
  aem6.3-author-vm:
    enabled: false
    install_dispatcher: false
    memory_size: 3072
    cpus: 1
    box_os: "centos"
    box_name: "centos-7.2-x64.box"
    box_url: "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box"
    gui: false
    installation_type: "author"
    sling_run_modes: "author,local"
    port: 4502
    min_heap: 512
    max_heap: 2048
    jvm_options: "-agentlib:jdwp=transport=dt_socket,address=30302,server=y,suspend=n" # address=<port> should be same as the one in http_cq_debug below
    license_url: "file:///vagrant/setup/aem/6.3/license.properties"
    jar_url: "file:///vagrant/setup/aem/6.3/AEM_6.3_Quickstart.jar"
    shared_folders:
      vm-software:
        host_path: "setup"
        vm_path: "/setup"
    install_packages: ["file:///vagrant/setup/aem/6.3/AEM-6.3-Service-Pack-1-6.3.1.zip"]
    jdk_version: '8'
    java:
        x86_64:
          url: "http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz"
          checksum: "6dbc56a0e3310b69e91bb64db63a485bd7b6a8083f08e48047276380a0e2021e"
        i586:
          url: "http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-i586.tar.gz"
          checksum: "cf69617a74cccb262f06f7948f38e1c004d2663801e7724e7a7a0dabeb48d7dc"        
    port_forwards:
      ssh:
        host_port:  2243
        guest_port: 22
      http:
        host_port:  8082
        guest_port: 80
      http_cq_deploy:
        host_port:  4502
        guest_port: 4502
      http_cq_debug:
        host_port:  30302
        guest_port: 30302 
    ip: 192.168.2.199
    host_name: "aem63.author.local.net"
  aem6.3-publish-vm:
    enabled: false
    install_dispatcher: true
    memory_size: 3072
    cpus: 1
    box_os: "centos"
    box_name: "centos-7.2-x64.box"
    box_url: "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box"
    gui: false
    installation_type: "publish"
    sling_run_modes: "publish,local"
    port: 4503
    min_heap: 512
    max_heap: 2048
    jvm_options: "-agentlib:jdwp=transport=dt_socket,address=30303,server=y,suspend=n" # address=<port> should be same as the one in http_cq_debug below
    license_url: "file:///setup/aem/6.3/license.properties"
    jar_url: "file:///setup/aem/6.3/AEM_6.3_Quickstart.jar"
    shared_folders:
      vm-software:
        host_path: "setup"
        vm_path: "/setup"
    install_packages: ["file:///vagrant/setup/aem/6.3/AEM-6.3-Service-Pack-1-6.3.1.zip"]
    jdk_version: '8'
    java:
        x86_64:
          url: "http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz"
          checksum: "6dbc56a0e3310b69e91bb64db63a485bd7b6a8083f08e48047276380a0e2021e"
        i586:
          url: "http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-i586.tar.gz"
          checksum: "cf69617a74cccb262f06f7948f38e1c004d2663801e7724e7a7a0dabeb48d7dc"
    port_forwards:
      ssh:
        host_port:  2244
        guest_port: 22
      http:
        host_port:  8001
        guest_port: 80
      http_cq_deploy:
        host_port:  4503
        guest_port: 4503
      http_cq_debug:
        host_port:  30303
        guest_port: 30303
    ip: 192.168.2.198
    host_name: "aem63.publish.local.net"